# Generated by Django 4.0.6 on 2022-09-21 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investment', '0004_delete_deposit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.PositiveBigIntegerField(verbose_name='거래금액')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.investment', verbose_name='투자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='고객')),
            ],
        ),
    ]
