# Generated by Django 4.0.6 on 2022-09-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0002_deposit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('validate', '검증 상태'), ('complete', '입금 완료'), ('fail', '입금 실패')], default='validate', max_length=128, verbose_name='상태'),
        ),
    ]
