# Generated by Django 4.0.6 on 2022-09-21 04:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='자산그륩명')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='증권사명')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=128, verbose_name='계좌명')),
                ('account_num', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(regex='^\\d+$')], verbose_name='계좌번호')),
                ('starting_fund', models.PositiveBigIntegerField(verbose_name='투자원금')),
                ('total_asset', models.PositiveBigIntegerField(verbose_name='계좌총자산')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.bank', verbose_name='증권사')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='고객')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='보유수량')),
                ('current_price', models.PositiveIntegerField(verbose_name='현재가')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.investment', verbose_name='투자')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='종목명')),
                ('isin', models.CharField(max_length=128, verbose_name='ISIN')),
                ('asset_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.assetgroup', verbose_name='자산그륩')),
                ('insvestment', models.ManyToManyField(related_name='stock', through='investment.InvestmentStock', to='investment.investment', verbose_name='보유종목')),
            ],
        ),
        migrations.AddField(
            model_name='investmentstock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.stock', verbose_name='보유종목'),
        ),
    ]
