# Generated by Django 4.0.6 on 2022-09-21 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetgroup',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='자산그륩명'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='증권사명'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='account_num',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d+$')], verbose_name='계좌번호'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='starting_fund',
            field=models.PositiveBigIntegerField(default=0, verbose_name='투자원금'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='total_asset',
            field=models.PositiveBigIntegerField(default=0, verbose_name='계좌총자산'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='isin',
            field=models.CharField(max_length=128, unique=True, verbose_name='ISIN'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='종목명'),
        ),
    ]
