# Generated by Django 4.0.6 on 2022-09-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_deposit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
